Repository thaisfrede/devops-aula07, pull requests merged in 2018-10, with the labels that each got.

#11 Update requisitos.md
  docs/requisitos.md
Labels: Análise

#13 Update arquitetura.md
  docs/arquitetura.md
Labels: Arquitetura

#15 Update jogovelha.py
  src/jogovelha.py
Labels: Programação

#18 Gerar Release V1.1
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: Operações
