Repository thaisfrede/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: Análise

#4 Create arquitetura.md
  docs/arquitetura.md
Labels: Arquitetura

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: Programação

#8 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: Testes

#9 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: Operações
